<h1 align="center">
  <img alt="CurrencyCopnverter" title="Currency Converter" src="/github/logo.png" width="220px" />
</h1>

<p align="center">
  <a href="#-tecnologias">Tecnologias</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
  <a href="#-projeto">Projeto</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
  <a href="#-layout">Layout</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
</p>

<br>

<p align="center">
  <img alt="dev.finances" src=".github/jobscalc.png" width="100%">
</p>

## 🚀 Tecnologias

Esse projeto foi desenvolvido com as seguintes tecnologias:

- HTML
- CSS
- JavaScript


## 💻 Projeto

O Currency COnverter é uma aplicação para conversão de moedas, onde será possível selecionar diversas moedas utilizadas no mundo e converte-las para o real ou vice-versa utilizando uma API 💰


---

Feito com ♥ by Banzak :wave: